configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-polished-wind-a1qx3orq-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_7pLIwZFi3Bld
